"""stack update bookkeeping

Two tables for the same subject, kept apart by how long they live.

stack_version caches the last look at the checkout and at the branch, so the
interface can answer "is there something newer" without starting a container
on every page load.

stack_update exists because an update replaces the process running it. The job
that starts one cannot finish it - `docker compose up` takes the API container
down partway through - so the next process picks the outcome up from here. The
container id is the important column: the container outlives its caller, and
it is what still holds the exit code and the log when somebody comes back for
them.

Revision ID: b17d95c5b98e
Revises: c1f0a7d4e2b8
Create Date: 2026-08-27 12:54:43.841499
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b17d95c5b98e"
down_revision: str | None = "c1f0a7d4e2b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stack_version",
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("checkout_commit", sa.String(length=64), nullable=False),
        sa.Column("checkout_dirty", sa.Boolean(), nullable=False),
        sa.Column("remote_commit", sa.String(length=64), nullable=False),
        sa.Column("reachable", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("commits", sa.JSON(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stack_version")),
    )
    op.create_table(
        "stack_update",
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("container_id", sa.String(length=64), nullable=False),
        sa.Column("commit_from", sa.String(length=64), nullable=False),
        sa.Column("commit_to", sa.String(length=64), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column("checkout_dir", sa.Text(), nullable=False),
        sa.Column("log_cursor", sa.Integer(), nullable=False),
        sa.Column("settled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_stack_update_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stack_update")),
    )
    with op.batch_alter_table("stack_update", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stack_update_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stack_update_settled"), ["settled"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stack_update", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stack_update_settled"))
        batch_op.drop_index(batch_op.f("ix_stack_update_job_id"))

    op.drop_table("stack_update")
    op.drop_table("stack_version")
    # ### end Alembic commands ###
