"""availability monitoring

Four tables for one question - is this device switched on - deliberately
without a time series database. watch_state_interval is the point: one row
per uninterrupted stretch in one state, extended by every measurement that
agrees with it, so a printer that has been up since March is one row and not
a quarter of a million samples. ADR 0011 has the reasoning.

The partial unique index on watch_state_interval is load-bearing rather than
decorative. At most one interval per device may be open, and the ingest is
free to be simple because the database refuses the second one.

Revision ID: dc72e85ab7c5
Revises: e8b3f1a26c47
Create Date: 2026-09-01 17:05:37.532282
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "dc72e85ab7c5"
down_revision: str | None = "e8b3f1a26c47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watch_device",
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("probe_id", sa.String(length=26), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("failure_threshold", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["probe_id"],
            ["probe_record.id"],
            name=op.f("fk_watch_device_probe_id_probe_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_device")),
        sa.UniqueConstraint(
            "probe_id", "address", name="uq_watch_device_probe_address"
        ),
    )
    with op.batch_alter_table("watch_device", schema=None) as batch_op:
        batch_op.create_index("ix_watch_device_enabled", ["enabled"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_watch_device_probe_id"), ["probe_id"], unique=False
        )

    op.create_table(
        "watch_latency_bucket",
        sa.Column("device_id", sa.String(length=26), nullable=False),
        sa.Column("bucket_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.Column("min_ms", sa.Float(), nullable=False),
        sa.Column("max_ms", sa.Float(), nullable=False),
        sa.Column("total_ms", sa.Float(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["watch_device.id"],
            name=op.f("fk_watch_latency_bucket_device_id_watch_device"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_latency_bucket")),
        sa.UniqueConstraint(
            "device_id", "bucket_start", name="uq_watch_latency_bucket"
        ),
    )
    with op.batch_alter_table("watch_latency_bucket", schema=None) as batch_op:
        batch_op.create_index(
            "ix_watch_latency_bucket_start", ["bucket_start"], unique=False
        )

    op.create_table(
        "watch_observation",
        sa.Column("device_id", sa.String(length=26), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("rtt_ms", sa.Float(), nullable=True),
        sa.Column("consecutive_failures", sa.Integer(), nullable=False),
        sa.Column("resolved_address", sa.String(length=64), nullable=True),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["watch_device.id"],
            name=op.f("fk_watch_observation_device_id_watch_device"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_observation")),
        sa.UniqueConstraint("device_id", name=op.f("uq_watch_observation_device_id")),
    )
    op.create_table(
        "watch_state_interval",
        sa.Column("device_id", sa.String(length=26), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["watch_device.id"],
            name=op.f("fk_watch_state_interval_device_id_watch_device"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_watch_state_interval")),
    )
    with op.batch_alter_table("watch_state_interval", schema=None) as batch_op:
        batch_op.create_index(
            "ix_watch_state_interval_device_started",
            ["device_id", "started_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_watch_state_interval_open",
            ["device_id"],
            unique=True,
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watch_state_interval", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_watch_state_interval_open",
            sqlite_where=sa.text("ended_at IS NULL"),
            postgresql_where=sa.text("ended_at IS NULL"),
        )
        batch_op.drop_index("ix_watch_state_interval_device_started")

    op.drop_table("watch_state_interval")
    op.drop_table("watch_observation")
    with op.batch_alter_table("watch_latency_bucket", schema=None) as batch_op:
        batch_op.drop_index("ix_watch_latency_bucket_start")

    op.drop_table("watch_latency_bucket")
    with op.batch_alter_table("watch_device", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watch_device_probe_id"))
        batch_op.drop_index("ix_watch_device_enabled")

    op.drop_table("watch_device")
    # ### end Alembic commands ###
