"""initial schema

Revision ID: fc92d48b6910
Revises:
Create Date: 2026-08-02 22:41:06.388324
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "fc92d48b6910"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The audit table is append-only by contract. metadata.create_all installs
# these through a DDL listener; op.create_table does not, so a migrated
# database would quietly have an audit trail anyone could edit.
AUDIT_TRIGGERS = (
    """
    CREATE TRIGGER IF NOT EXISTS audit_event_no_update
    BEFORE UPDATE ON audit_event
    BEGIN
        SELECT RAISE(ABORT, 'audit_event is append-only');
    END
    """,
    """
    CREATE TRIGGER IF NOT EXISTS audit_event_no_delete
    BEFORE DELETE ON audit_event
    BEGIN
        SELECT RAISE(ABORT, 'audit_event is append-only');
    END
    """,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert",
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_ref", sa.String(length=128), nullable=False),
        sa.Column("object_label", sa.String(length=255), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert")),
        sa.UniqueConstraint("kind", "object_ref", name=op.f("uq_alert_kind")),
    )
    op.create_table(
        "audit_event",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.String(length=26), nullable=True),
        sa.Column("actor_name", sa.String(length=64), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=32), nullable=False),
        sa.Column("object_id", sa.String(length=128), nullable=True),
        sa.Column("object_label", sa.String(length=255), nullable=True),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("result", sa.String(length=16), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("job_id", sa.String(length=26), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index("ix_audit_event_actor", ["actor_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_event_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_event_object", ["object_type", "object_id"], unique=False
        )
        batch_op.create_index("ix_audit_event_ts", ["ts"], unique=False)

    op.create_table(
        "login_attempt",
        sa.Column("username_folded", sa.String(length=64), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempt")),
    )
    with op.batch_alter_table("login_attempt", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempt_attempted_at"), ["attempted_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_login_attempt_username_folded"),
            ["username_folded"],
            unique=False,
        )

    op.create_table(
        "probe_record",
        sa.Column("nats_username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_probe_record")),
        sa.UniqueConstraint(
            "nats_username", name=op.f("uq_probe_record_nats_username")
        ),
    )
    op.create_table(
        "setting",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("updated_by", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_setting")),
    )
    op.create_table(
        "web_user",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("username_folded", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_user")),
        sa.UniqueConstraint(
            "username_folded", name=op.f("uq_web_user_username_folded")
        ),
    )
    op.create_table(
        "job",
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.Column("target_label", sa.String(length=255), nullable=True),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("requested_by_id", sa.String(length=26), nullable=True),
        sa.Column("requested_by_name", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("current_step", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_reason_key", sa.String(length=128), nullable=True),
        sa.Column("blocked_by_job_id", sa.String(length=26), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_params", sa.JSON(), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("retry_of_job_id", sa.String(length=26), nullable=True),
        sa.Column("cancel_requested", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["web_user.id"],
            name=op.f("fk_job_requested_by_id_web_user"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_status_created", ["status", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_job_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            "ix_job_type_created", ["type", "created_at"], unique=False
        )

    op.create_table(
        "probe_desired_state",
        sa.Column("probe_id", sa.String(length=26), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("author_id", sa.String(length=26), nullable=True),
        sa.Column("author_name", sa.String(length=64), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["web_user.id"],
            name=op.f("fk_probe_desired_state_author_id_web_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["probe_id"],
            ["probe_record.id"],
            name=op.f("fk_probe_desired_state_probe_id_probe_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_probe_desired_state")),
        sa.UniqueConstraint(
            "probe_id", "version", name=op.f("uq_probe_desired_state_probe_id")
        ),
    )
    with op.batch_alter_table("probe_desired_state", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_probe_desired_state_probe_id"), ["probe_id"], unique=False
        )

    op.create_table(
        "probe_observed_state",
        sa.Column("probe_id", sa.String(length=26), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reachable", sa.Boolean(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["probe_id"],
            ["probe_record.id"],
            name=op.f("fk_probe_observed_state_probe_id_probe_record"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_probe_observed_state")),
        sa.UniqueConstraint("probe_id", name=op.f("uq_probe_observed_state_probe_id")),
    )
    op.create_table(
        "saved_view",
        sa.Column("owner_id", sa.String(length=26), nullable=True),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["web_user.id"],
            name=op.f("fk_saved_view_owner_id_web_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_view")),
        sa.UniqueConstraint(
            "owner_id", "scope", "name", name=op.f("uq_saved_view_owner_id")
        ),
    )
    op.create_table(
        "session",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["web_user.id"],
            name=op.f("fk_session_user_id_web_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_session_token_hash")),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index("ix_session_expires_at", ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_session_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_role",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["web_user.id"],
            name=op.f("fk_user_role_user_id_web_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role")),
        sa.UniqueConstraint("user_id", "role", name=op.f("uq_user_role_user_id")),
    )
    with op.batch_alter_table("user_role", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_role_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "deployment",
        sa.Column("sensor_name", sa.String(length=64), nullable=False),
        sa.Column("sensor_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("requested_by_name", sa.String(length=64), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_deployment_job_id_job"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment")),
    )
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.create_index("ix_deployment_created", ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_deployment_job_id"), ["job_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_deployment_sensor_name"), ["sensor_name"], unique=False
        )

    op.create_table(
        "job_event",
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("step", sa.String(length=64), nullable=True),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_job_event_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_event")),
    )
    with op.batch_alter_table("job_event", schema=None) as batch_op:
        batch_op.create_index(
            "ix_job_event_job_sequence", ["job_id", "sequence"], unique=False
        )

    op.create_table(
        "job_step",
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_label", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_job_step_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_step")),
        sa.UniqueConstraint("job_id", "position", name=op.f("uq_job_step_job_id")),
    )
    with op.batch_alter_table("job_step", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_job_step_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "resource_lock",
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("job_id", sa.String(length=26), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
            name=op.f("fk_resource_lock_job_id_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resource_lock")),
        sa.UniqueConstraint(
            "resource_type", "resource_id", name=op.f("uq_resource_lock_resource_type")
        ),
    )
    with op.batch_alter_table("resource_lock", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_resource_lock_job_id"), ["job_id"], unique=False
        )

    op.create_table(
        "deployment_target",
        sa.Column("deployment_id", sa.String(length=26), nullable=False),
        sa.Column("probe_id", sa.String(length=26), nullable=False),
        sa.Column("probe_label", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("previous_version", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_params", sa.JSON(), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployment.id"],
            name=op.f("fk_deployment_target_deployment_id_deployment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_target")),
        sa.UniqueConstraint(
            "deployment_id", "probe_id", name=op.f("uq_deployment_target_deployment_id")
        ),
    )
    with op.batch_alter_table("deployment_target", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deployment_target_deployment_id"),
            ["deployment_id"],
            unique=False,
        )

    if op.get_bind().dialect.name == "sqlite":
        for statement in AUDIT_TRIGGERS:
            op.execute(statement)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS audit_event_no_delete")
        op.execute("DROP TRIGGER IF EXISTS audit_event_no_update")
    with op.batch_alter_table("deployment_target", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployment_target_deployment_id"))

    op.drop_table("deployment_target")
    with op.batch_alter_table("resource_lock", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_resource_lock_job_id"))

    op.drop_table("resource_lock")
    with op.batch_alter_table("job_step", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_job_step_job_id"))

    op.drop_table("job_step")
    with op.batch_alter_table("job_event", schema=None) as batch_op:
        batch_op.drop_index("ix_job_event_job_sequence")

    op.drop_table("job_event")
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deployment_sensor_name"))
        batch_op.drop_index(batch_op.f("ix_deployment_job_id"))
        batch_op.drop_index("ix_deployment_created")

    op.drop_table("deployment")
    with op.batch_alter_table("user_role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_role_user_id"))

    op.drop_table("user_role")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_user_id"))
        batch_op.drop_index("ix_session_expires_at")

    op.drop_table("session")
    op.drop_table("saved_view")
    op.drop_table("probe_observed_state")
    with op.batch_alter_table("probe_desired_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_probe_desired_state_probe_id"))

    op.drop_table("probe_desired_state")
    with op.batch_alter_table("job", schema=None) as batch_op:
        batch_op.drop_index("ix_job_type_created")
        batch_op.drop_index(batch_op.f("ix_job_target_id"))
        batch_op.drop_index("ix_job_status_created")

    op.drop_table("job")
    op.drop_table("web_user")
    op.drop_table("setting")
    op.drop_table("probe_record")
    with op.batch_alter_table("login_attempt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempt_username_folded"))
        batch_op.drop_index(batch_op.f("ix_login_attempt_attempted_at"))

    op.drop_table("login_attempt")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_event_ts")
        batch_op.drop_index("ix_audit_event_object")
        batch_op.drop_index(batch_op.f("ix_audit_event_job_id"))
        batch_op.drop_index("ix_audit_event_actor")

    op.drop_table("audit_event")
    op.drop_table("alert")
    # ### end Alembic commands ###
